# Powershell Module Pipeline

# Module version
name: 0.0.$(rev:r)
resources:
- repo: self
pool:
  vmImage: 'windows-latest'
steps:
- powershell: ./ build.ps1
  displayName: 'PowerShell Script'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Artifacts'
  inputs:
    PathtoPublish: Output

    ArtifactName: Artifacts


- task: PublishTestResults@2
  displayName: 'Publish Test Results **\TestResults*.xml'
  inputs:
    testResultsFormat: NUnit

    testResultsFiles: '**\TestResults*.xml'

    mergeTestResults: true

    testRunTitle: '$(Build.BuildNumber)'


